# Generated by Django 3.2.2 on 2021-05-17 10:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_product.basecategory_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Base Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Base Products',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseproduct')),
                ('brand', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('display_size', models.CharField(help_text='Display size in millimeters', max_length=255)),
                ('display_resolution', models.CharField(help_text='Display resolution', max_length=255)),
                ('storage', models.PositiveIntegerField(help_text='phone storage memory size in "GB"')),
                ('ram_memory', models.PositiveIntegerField(help_text='Random Access Memory size in GygaBytes "GB"')),
                ('color', models.CharField(max_length=150)),
                ('cellular', multiselectfield.db.fields.MultiSelectField(choices=[(1, '5G'), (2, '4G'), (3, 'LTE'), (4, 'GPRS'), (5, 'DUAL-SIM')], max_length=9)),
                ('weight', models.DecimalField(decimal_places=2, help_text='weight of mobile in gramms', max_digits=10)),
                ('size', models.CharField(help_text="Size of device' proportions in millimeters", max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Mobile Phones',
            },
            bases=('product.baseproduct',),
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('basecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basecategory')),
            ],
            options={
                'verbose_name_plural': 'Parent Categories',
            },
            bases=('product.basecategory',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseproduct')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
            bases=('product.baseproduct',),
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_product.imagealbum_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=product.models.get_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=product.models.get_upload_path)),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.imagealbum')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_product.image_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='product.imagealbum'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.image'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_product.baseproduct_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('basecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basecategory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.parentcategory')),
            ],
            options={
                'verbose_name_plural': 'Child Categories',
            },
            bases=('product.basecategory',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basecategory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.childcategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=('product.basecategory',),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category'),
        ),
    ]
