# Generated by Django 3.2.2 on 2021-05-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='image',
        ),
    ]
