# Generated by Django 3.2.2 on 2021-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210517_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
