# Generated by Django 3.2.2 on 2021-05-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproductmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='weight of mobile in gramms', max_digits=10, null=True),
        ),
    ]
