# Generated by Django 3.2.2 on 2021-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210517_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
